language: python

sudo: false

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install numpy
  - pip install scipy
  - pip install codecov

script:
  - cd HydroErr/tests
  - coverage run tests.py

after_success:
- codecov
