name: Publish

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token $UV_PYPI_TOKEN
